import { useState } from "react";
import { getToken, getUser } from "../services/authService";
import { useLocation, useNavigate } from "react-router-dom";

export default function Feedback() {
  const user = getUser();
  const location = useLocation();
  const navigate = useNavigate();
  const fromAction = new URLSearchParams(location.search).has("source");
  const [form, setForm] = useState({ name: user?.name || "", email: user?.email || "", category: "GENERAL", rating: 5, message: "" });
  const [state, setState] = useState("");
  const update = e => setForm({ ...form, [e.target.name]: e.target.value });
  async function submit(e) { e.preventDefault(); setState("Sending…"); const token = getToken(); const res = await fetch(`${import.meta.env.VITE_API_URL}/api/feedback`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(form) }); const data = await res.json().catch(() => ({})); setState(res.ok ? "Thanks — your feedback has been received." : data.message || "Could not send feedback."); }
  const formContent = <form onSubmit={submit} className="feedback-form">{!user && <div className="feedback-row"><input name="name" required value={form.name} onChange={update} placeholder="Your name" /><input name="email" type="email" required value={form.email} onChange={update} placeholder="Your email" /></div>}<select name="category" value={form.category} onChange={update}>{["GENERAL", "BUG", "FEATURE", "PAYMENT", "OTHER"].map(x => <option key={x}>{x}</option>)}</select><label>How would you rate us? <span>{form.rating}/5</span><input className="feedback-range" name="rating" type="range" min="1" max="5" value={form.rating} onChange={update} /></label><textarea name="message" required minLength={10} maxLength={2000} rows={7} value={form.message} onChange={update} placeholder="What did you enjoy? What should we improve?" /><button type="submit">Send feedback</button>{state && <p className="feedback-state">{state}</p>}</form>;
  return <main className="feedback-page"><style>{`.feedback-page{min-height:100vh;background:radial-gradient(circle at 10% 0%,#2b2140 0,#080910 42%);color:#f5f1ea;padding:clamp(28px,8vw,90px) 20px;font-family:DM Sans,sans-serif}.feedback-card{max-width:650px;margin:auto;background:rgba(20,21,31,.9);border:1px solid rgba(232,201,106,.22);border-radius:28px;padding:clamp(25px,5vw,48px);box-shadow:0 25px 80px #0008}.feedback-kicker{color:#e8c96a;text-transform:uppercase;letter-spacing:2px;font-size:12px;font-weight:700}.feedback-card h1{font-family:Syne,sans-serif;font-size:clamp(30px,6vw,48px);margin:10px 0}.feedback-card p{color:#aaa7a0;line-height:1.6}.feedback-form{display:grid;gap:16px;margin-top:28px}.feedback-form input,.feedback-form select,.feedback-form textarea{width:100%;border:1px solid #ffffff20;border-radius:12px;background:#ffffff08;color:#f5f1ea;padding:14px;font:inherit}.feedback-form select option{color:#111}.feedback-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.feedback-form label{color:#aaa7a0}.feedback-form label span{float:right;color:#e8c96a;font-weight:700}.feedback-range{display:block!important;padding:0!important;margin-top:12px;accent-color:#e8c96a}.feedback-form button{border:0;border-radius:999px;padding:15px;background:linear-gradient(135deg,#e8c96a,#fff0a5);font-weight:800;cursor:pointer}.feedback-state{color:#6bf0a0!important}@media(max-width:550px){.feedback-row{grid-template-columns:1fr}}`}</style><div className="feedback-card"><span className="feedback-kicker">Your voice matters</span><h1>Help us build a better Tictify</h1><p>{fromAction ? "Thanks for using Tictify. Tell us about your experience — this is optional and takes less than a minute." : "Tell us what is working and how we can improve."}</p>{formContent}<button onClick={() => navigate(-1)} style={{ marginTop: 16, background: "none", border: 0, color: "#aaa7a0", cursor: "pointer" }}>Maybe later</button></div></main>;
}
